### ISSUE TITLE
Critical Flow Documentation - Figma Block

### ISSUE THREAD

**Issue by ankitguptaindia** [10up/figma-block#23]
### Objective: 

This GitHub issue will serve as a task to prepare Critical Flow (also known as Test Cases) for this repository/plugin.
- **[Guide for Creating Critical Flow of 10up OSS Projects](https://docs.google.com/document/d/1rNv_jHxsQT-AKSJ9QC2HGH-rRKAlTJOoGBtP10w_zV0/edit#heading=h.ucn4farfwxyf).**

This plugin doesn't have Wiki Pages enabled. Please add test cases by adding Pull Request. Example: https://github.com/10up/google-workspace-groups/pull/46 

**_Feel free to DM me or the OSS channel for any questions or doubt._** 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeffpaul** [comment]
Repo is now public, so these can get added to https://github.com/10up/figma-block/wiki

**Comment by ankitguptaindia** [comment]
Test cases have been added to the WIki pages. https://github.com/10up/figma-block/wiki/Critical-Flow--%E2%80%90-Figma-Block
