### ISSUE TITLE
Update naming

### ISSUE THREAD

**Issue by jeffpaul** [10up/figma-block#26]
### Is your enhancement related to a problem? Please describe.

Per feedback from the WP.org Plugin Review Team we need to do the following:
- [ ] Update plugin name in the `readme.txt` file to "Embed Block for Figma"
- [ ] Update plugin name in the `figma-block.php` file to "Embed Block for Figma"
- [ ] Update plugin file name from `figma-block.php` to `embed-block-figma.php` and any other references to `figma-block.php` should similarly be updated
- [ ] Update GitHub repo name from `figma-block` to `embed-block-figma`
- [ ] 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thrijith** [comment]
Hi @jeffpaul 

This PR adds the name change https://github.com/10up/figma-block/pull/28, issue with current changes in the PR is that if anyone has the plugin already active on the site it will deactivate on update as the plugin file name and plugin folder name has changed.

Should I look into make sure the plugin is kept active in case of update?

**Comment by jeffpaul** [comment]
@thrijith there's probably only a very small number of folks already using the plugin, since we've not announced it or released to dotorg so I think we're ok skipping that step (and hopefully anyone that happens to would see it deactivate and reactivate it anyway).
