### ISSUE TITLE
Add WordPress Playground integration

### ISSUE THREAD

**Issue by jeffpaul** [10up/figma-block#27]
### Is your enhancement related to a problem? Please describe.

- [ ] add blueprint to dotorg folder
- [ ] enable preview on dotorg (will be blocked by dotorg plugin approval & repo creation)
- [ ] add repo badge to playground

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thrijith** [comment]
The PR adds the required file for setting the plugin up for playground but it is not functional now, I tried using the release zip to use it as a plugin installation zip but it didn't work, to test it currently, we'll have to add the zip directly in the repo.

Once the plugin is deployed t production the following changes need to happen, 

- Rename `https://img.shields.io/github/v/release/10up/figma-block` to `https://img.shields.io/wordpress/plugin/v/<plugin-slug>` in README.MD
